import { describe, it, expect } from "vitest";
import { isValidSessionToken, unauthorizedResponse } from "./auth";

describe("auth", () => {
  describe("isValidSessionToken", () => {
    it("should return true for valid 64-char hex token", () => {
      const validToken = "a".repeat(64);
      expect(isValidSessionToken(validToken)).toBe(true);
    });

    it("should return true for valid token with mixed hex chars", () => {
      const validToken = "0123456789abcdef".repeat(4);
      expect(isValidSessionToken(validToken)).toBe(true);
    });

    it("should return false for undefined", () => {
      expect(isValidSessionToken(undefined)).toBe(false);
    });

    it("should return false for empty string", () => {
      expect(isValidSessionToken("")).toBe(false);
    });

    it("should return false for token shorter than 64 chars", () => {
      expect(isValidSessionToken("a".repeat(63))).toBe(false);
    });

    it("should return false for token longer than 64 chars", () => {
      expect(isValidSessionToken("a".repeat(65))).toBe(false);
    });

    it("should return false for non-hex characters", () => {
      // 'g' is not a valid hex character
      expect(isValidSessionToken("g".repeat(64))).toBe(false);
    });

    it("should return false for uppercase hex (case sensitive)", () => {
      // The regex uses lowercase only: [a-f0-9]
      expect(isValidSessionToken("A".repeat(64))).toBe(false);
    });

    it("should return false for legacy 'authenticated' token", () => {
      expect(isValidSessionToken("authenticated")).toBe(false);
    });

    it("should return false for spaces", () => {
      expect(isValidSessionToken(" ".repeat(64))).toBe(false);
    });

    it("should return false for special characters", () => {
      expect(isValidSessionToken("!@#$%^&*()_+-=".repeat(5))).toBe(false);
    });

    it("should return true for valid token generated by generateSecureToken", () => {
      // generateSecureToken(32) produces 64 lowercase hex chars
      const crypto = require("crypto");
      const token = crypto.randomBytes(32).toString("hex");
      expect(isValidSessionToken(token)).toBe(true);
    });
  });

  describe("unauthorizedResponse", () => {
    it("should return 401 status", async () => {
      const response = unauthorizedResponse();
      expect(response.status).toBe(401);
    });

    it("should return JSON body with error message", async () => {
      const response = unauthorizedResponse();
      const body = await response.json();
      expect(body.error).toBe("Unauthorized");
    });

    it("should have application/json content type", () => {
      const response = unauthorizedResponse();
      expect(response.headers.get("content-type")).toContain("application/json");
    });
  });
});
