import fs from "fs/promises";
import path from "path";
import { config } from "./config";
import type { SyncManifest, SyncAlbum, SyncPhoto } from "./types";

/**
 * Load the existing manifest from disk, or return an empty one
 */
export async function loadManifest(): Promise<SyncManifest> {
  try {
    const data = await fs.readFile(config.manifestPath, "utf-8");
    return JSON.parse(data);
  } catch {
    // No existing manifest, return empty
    return {
      lastUpdated: new Date().toISOString(),
      albums: [],
      photos: [],
      chapters: {},
    };
  }
}

/**
 * Save the manifest to disk
 */
export async function saveManifest(manifest: SyncManifest): Promise<void> {
  // Ensure directory exists
  await fs.mkdir(path.dirname(config.manifestPath), { recursive: true });

  // Update timestamp
  manifest.lastUpdated = new Date().toISOString();

  // Write manifest
  await fs.writeFile(
    config.manifestPath,
    JSON.stringify(manifest, null, 2),
    "utf-8"
  );

  console.log(`Manifest saved to ${config.manifestPath}`);
}

/**
 * Update or add an album to the manifest
 */
export function updateAlbum(
  manifest: SyncManifest,
  album: SyncAlbum
): SyncManifest {
  const existingIndex = manifest.albums.findIndex((a) => a.id === album.id);

  if (existingIndex >= 0) {
    manifest.albums[existingIndex] = album;
  } else {
    manifest.albums.push(album);
  }

  return manifest;
}

/**
 * Update or add photos for an album
 */
export function updatePhotos(
  manifest: SyncManifest,
  albumId: string,
  photos: SyncPhoto[]
): SyncManifest {
  // Remove old photos for this album
  manifest.photos = manifest.photos.filter((p) => p.albumId !== albumId);

  // Add new photos
  manifest.photos.push(...photos);

  return manifest;
}

/**
 * Remove an album and its photos from the manifest
 */
export function removeAlbum(
  manifest: SyncManifest,
  albumId: string
): SyncManifest {
  manifest.albums = manifest.albums.filter((a) => a.id !== albumId);
  manifest.photos = manifest.photos.filter((p) => p.albumId !== albumId);
  delete manifest.chapters[albumId];

  return manifest;
}

/**
 * Get photos for a specific album
 */
export function getAlbumPhotos(
  manifest: SyncManifest,
  albumId: string
): SyncPhoto[] {
  return manifest.photos
    .filter((p) => p.albumId === albumId)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}

/**
 * Generate TypeScript data file from manifest for static site generation
 */
export async function generateDataFile(manifest: SyncManifest): Promise<void> {
  const dataPath = path.join(process.cwd(), "src", "lib", "synced-data.ts");

  const content = `// Auto-generated by sync service - DO NOT EDIT
// Last updated: ${manifest.lastUpdated}

import type { Album, Photo, Chapter } from "./types";

export const albums: Album[] = ${JSON.stringify(
    manifest.albums.map((a) => ({
      id: a.id,
      slug: a.slug,
      title: a.title,
      subtitle: a.subtitle,
      description: a.description,
      location: a.location,
      date: a.date,
      coverImage: a.coverImage,
      photoCount: a.photoCount,
      featured: a.featured,
    })),
    null,
    2
  )};

export const photos: Photo[] = ${JSON.stringify(
    manifest.photos.map((p) => ({
      id: p.id,
      title: p.title,
      description: p.description,
      src: p.src,
      metadata: p.metadata,
      albumId: p.albumId,
    })),
    null,
    2
  )};

export const chapters: Record<string, Chapter[]> = ${JSON.stringify(
    Object.fromEntries(
      Object.entries(manifest.chapters).map(([albumId, chaps]) => [
        albumId,
        chaps.map((c) => ({
          id: c.id,
          title: c.title,
          narrative: c.narrative,
          photos: manifest.photos.filter((p) => c.photoIds.includes(p.id)),
        })),
      ])
    ),
    null,
    2
  )};

// Helper functions
export function getAlbums(): Album[] {
  return albums;
}

export function getAlbumBySlug(slug: string): Album | undefined {
  return albums.find((a) => a.slug === slug);
}

export function getPhotosByAlbum(albumId: string): Photo[] {
  return photos.filter((p) => p.albumId === albumId);
}

export function getPhotoById(id: string): Photo | undefined {
  return photos.find((p) => p.id === id);
}

export function getChaptersByAlbum(albumSlug: string): Chapter[] {
  const album = albums.find((a) => a.slug === albumSlug);
  if (!album) return [];
  return chapters[album.id] || [];
}

export function getFeaturedAlbum(): Album | undefined {
  return albums.find((a) => a.featured) || albums[0];
}
`;

  await fs.writeFile(dataPath, content, "utf-8");
  console.log(`Data file generated at ${dataPath}`);
}
